### ISSUE TITLE
CRITICAL BUG

### ISSUE THREAD

**Issue by Johnamoroso** [BitcoinMafia/SpareCoinsExt#4] opened 2013-12-11 22:16 UTC
Uncaught TypeError: Cannot read property 'passwordDigest' of undefined

chrome-extension://nhkolgoaflkjhfkamdhiahingnendokj/lib/sparecoins.js

118

**Comment by sidazhang** [comment] 2013-12-11 22:31
@Johnamoroso , thanks for reporting this. What were you doing when you saw this?

And also, version of chrome + os?

**Comment by Johnamoroso** [comment] 2013-12-11 22:39
![schermata 12-2456638 alle 22 33 33](https://f.cloud.github.com/assets/4113607/1728754/90a1ffcc-62b4-11e3-8921-f9bb8ca73b69.png)

Yes, it is Chrome Os version 28.0.1500.95

**Comment by scottlingran** [comment] 2013-12-11 22:44
It seems like the extension thinks you haven't set a password, OR, the passwordDigest was cleared and you tried to hit a link requiring Auth.

Could you tell us how this happened?

**Comment by Johnamoroso** [comment] 2013-12-11 22:51
as soon as activated this message appears. I haven't got to do anything else.

**Comment by scottlingran** [comment] 2013-12-13 05:57
@Johnamoroso, ok, couldn't reproduce the bug, but added a fix where that error occurs and returned on that. Deployed to Chrome Store (v1.0.11). Let me know if it's still an issue.

**Comment by Johnamoroso** [comment] 2013-12-13 11:30
Yeah! It works correctly now!

**Comment by sidazhang** [comment] 2013-12-13 18:41
@Johnamoroso awesome! I will close this now!

Thanks for submitting the issue :)

**Closed as completed by sidazhang** 2013-12-13 18:41 UTC
Labels: bug
